[profile.default]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 10_000
ignored_warnings_from = ["src/PX.sol"]

build_info = true
extra_output = ["storageLayout"]


[fmt]
line_length = 120
tab_width = 4
